version: 2
jobs:
  build:
    branches:
      only:
        - wip
    docker:
      - image: circleci/node:7.10
    working_directory: ~/server

    steps: 
      - checkout
      - run: npm install
      # - run: npm run nstart